/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.bancolombia;

import co.com.bancolombia.task.GenerateModelTask;
import co.com.bancolombia.task.GenerateStructureTask;
import co.com.bancolombia.task.validateStructureTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.Task;
import org.gradle.api.tasks.TaskContainer;

/**
 * A simple 'hello world' plugin.
 */
public class PluginCleanPlugin implements Plugin<Project> {

    private static String taskGroup = "Clean Architecture";

    public void apply(Project project) {

        // Register a task
        TaskContainer tasks = project.getTasks();

        Task generateStructure = tasks.create("cleanArchitecture", GenerateStructureTask.class);
        generateStructure.setGroup(taskGroup);
        generateStructure.setDescription("Scaffolding clean architecture project");

        Task generateModel = tasks.create("generateModel", GenerateModelTask.class);
        generateModel.setGroup(taskGroup);
        generateModel.setDescription("Generate model project in domain layer");

        Task validateStructure = tasks.create("validateStructure", validateStructureTask.class);
        validateStructure.setGroup(taskGroup);
        validateStructure.setDescription("Validate that project references are not violated");


    }
}
