server:
  port: 8080
spring:
  application:
    name: "ExampleRedis"
  devtools:
    add-properties: false
  profiles:
    include: null
  redis:
    host: "localhost"
    port: 6379

management:
  endpoint:
    health:
      enabled: true
      show-details: never
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
