server:
  port: 8080
spring:
  application:
    name: "RedisScaffoldCA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  redis:
    host: "localhost"
    port: 6379
