/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.bancolombia;



/**
 * A simple functional test for the 'co.com.bancolombia.greeting' plugin.
 */
public class PluginCleanPluginFunctionalTest {

}
