{{#java8}}
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
{{/java8}}
{{#java11}}
FROM adoptopenjdk/openjdk11-openj9:alpine-slim
{{/java11}}
{{#java17}}
FROM eclipse-temurin:17-jdk-alpine
{{/java17}}
VOLUME /tmp
# Replace with a non-root user to avoid running the container with excessive privileges
# COPY --chown=appuser:appuser {{projectName}}.jar app.jar
COPY {{projectName}}.jar app.jar
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom"
# Replace with a non-root user to avoid running the container with excessive privileges
# USER appuser
ENTRYPOINT [ "/bin/sh", "-c", "/opt/java/openjdk/bin/java $JAVA_OPTS -jar /app.jar" ]