{{#java8}}
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
{{/java8}}
{{#java11}}
FROM adoptopenjdk/openjdk11-openj9:alpine-slim
{{/java11}}
{{#java17}}
FROM amazoncorretto:17-alpine
{{/java17}}
VOLUME /tmp
COPY *.jar app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=" -Xshareclasses:name=cacheapp,cacheDir=/cache,nonfatal -XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -jar app.jar" ]
