/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.bancolombia;

import org.gradle.api.Task;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'co.com.bancolombia.greeting' plugin.
 */
public class PluginCleanPluginTest {
    @Test
    public void pluginRegistersATask() {

        // Arrange
        String taskGroup = "Clean Architecture";
        String descriptionTask = "Scaffold Project Clean Architecture";
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("co.com.bancolombia.scaffoldJavaCleanArchitecture");

        // Act
        Task task = project.getTasks().findByName("cleanArchitecture");

        //Assert
        assertNotNull(task);
        assertEquals(taskGroup, task.getGroup());
        assertEquals(descriptionTask, task.getDescription());
    }

}
